#project: RnaSeqData/Project_McCue_Project_022
#project: RnaSeqData/Project_McCue_Project_002
#project: RnaSeqData/130924_700506R_0305_AC2LGJACXX/Project_McCue_Project_015
#project: RnaSeqData/130118_SN261_0475_BC1PBAACXX/Project_McCue_Project_007
#project: RnaSeqData/121121_SN1073_0299_AD1HCMACXX/Project_McCue_Project_009
project: RnaSeqData/121108_SN1073_0296_BC1C80ACXX/Project_McCue_Project_007

#project: RnaSeqData/120924_SN261_0451_AC14UWACXX/Project_McCue_Project_002
#project: RnaSeqData/120817_SN1073_0279_BC14UVACXX/Project_McCue_Project_002
#project: RnaSeqData/120703_SN261_0441_BD10CNACXX/Project_McCue_Project_002
#project: RnaSeqData/120622_SN261_0440_AD10CBACXX/Project_McCue_Project_002
